FROM mcr.microsoft.com/devcontainers/typescript-node:0-18

ENV http_proxy http://proxy.nas.medcity.net:80
ENV https_proxy http://proxy.nas.medcity.net:80
ENV no_proxy *.medcity.net,*.hca.corpad.net,localhost,127.0.0.1