name: Unit Test
  
env:
  # Build Variables
  NODE_VERSION: '18'  

on:
  pull_request:
    branches:
      - main
      - release/*

jobs:
  build:
    runs-on: [self-hosted, Linux, X64, enterprise, onprem]
    environment: development

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: 'Setup NPM ${{ env.NODE_VERSION }}'
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Install'
      run: npm install

    - name: 'Lint'
      run: npm run lint
      
    - name: 'Unit Test'
      run: npm run test:unit
